name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'v18.15.0'

    - name: Check Node.js and npm versions
      run: |
        node --version
        npm --version

    - name: npm ci and npm run build
        run: |
          pwd
          cd src/angular
          npm ci
          npm run build:ci
          cd ../..
          pwd

    - name: Maven Clean Package Jar
      run: |
        ./mvnw clean package -P build-copy-angular
