name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Remove node_modules and reinstall dependencies
      run: |
        cd src/angular
        ls -al
        rm -rf node_modules
        npm install
        cd ..

    - name: Check Node.js and npm versions
      run: |
        node --version
        npm --version

    - name: Maven Clean Package Jar
      run: |
        ./mvnw clean package -P build-copy-angular
